# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(715, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 720, 440))
        self.widget.setStyleSheet("QPushButton#button{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#button:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#button:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.widget.setObjectName("widget")
        self.label_g = QtWidgets.QLabel(self.widget)
        self.label_g.setGeometry(QtCore.QRect(10, 10, 691, 381))
        self.label_g.setStyleSheet("border-image: url(:/image/recycle.png);\n"
"border-radius:20px;\n"
"")
        self.label_g.setText("")
        self.label_g.setObjectName("label_g")
        self.button = QtWidgets.QPushButton(self.widget)
        self.button.setGeometry(QtCore.QRect(50, 280, 281, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button.setFont(font)
        self.button.setObjectName("button")
        self.trangthai = QtWidgets.QLabel(self.widget)
        self.trangthai.setGeometry(QtCore.QRect(80, 110, 221, 138))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.trangthai.setFont(font)
        self.trangthai.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.trangthai.setLineWidth(1)
        self.trangthai.setAlignment(QtCore.Qt.AlignCenter)
        self.trangthai.setObjectName("trangthai")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 100, 311, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tenkhachhang = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tenkhachhang.setFont(font)
        self.tenkhachhang.setAutoFillBackground(False)
        self.tenkhachhang.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.tenkhachhang.setAlignment(QtCore.Qt.AlignCenter)
        self.tenkhachhang.setObjectName("tenkhachhang")
        self.gridLayout.addWidget(self.tenkhachhang, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.label_3.setLineWidth(1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.soluongchai = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.soluongchai.setFont(font)
        self.soluongchai.setAutoFillBackground(False)
        self.soluongchai.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.soluongchai.setAlignment(QtCore.Qt.AlignCenter)
        self.soluongchai.setObjectName("soluongchai")
        self.gridLayout.addWidget(self.soluongchai, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.label_4.setLineWidth(1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.soluonglon = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.soluonglon.setFont(font)
        self.soluonglon.setAutoFillBackground(False)
        self.soluonglon.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.soluonglon.setAlignment(QtCore.Qt.AlignCenter)
        self.soluonglon.setObjectName("soluonglon")
        self.gridLayout.addWidget(self.soluonglon, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.label_5.setLineWidth(1)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(110, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.label_6.setLineWidth(1)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button.setText(_translate("MainWindow", "Đăng xuất"))
        self.trangthai.setText(_translate("MainWindow", "Xin mời quét thẻ"))
        self.label.setText(_translate("MainWindow", "Tên khách hàng"))
        self.tenkhachhang.setText(_translate("MainWindow", "-"))
        self.label_3.setText(_translate("MainWindow", "Số lượng chai"))
        self.soluongchai.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "Số lượng lon"))
        self.soluonglon.setText(_translate("MainWindow", "-"))
        self.label_5.setText(_translate("MainWindow", "Máy thu gom chai nhựa"))
        self.label_6.setText(_translate("MainWindow", "lon bia"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
